#server:
#  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_schema: market_schema
